### ISSUE TITLE
convert breaks defun with empty arg list

### ISSUE THREAD

**Issue by s-kostyaev** [conao3/leaf-convert.el#58]
Hi! Thank you for this cool project.
Today I have used it to migrate my own configuration to `leaf`. And I have found issue:
this:
```elisp
(defun some-name ()
  body)
```
makes into this:
```elisp
(defun some-name nil
  body)
```
and it breaks new configuration.

**Comment by conao3** [comment]
`nil `and `()` are the same, only the expression difference, see this result.

```emacs-lisp
(equal
 '(defun some-name ()
    body)
 '(defun some-name nil
    body))
;;=> t
```

Currently, it is difficult to output `()` instead of `nil`...

**Comment by s-kostyaev** [comment]
I can provide workaround to fix it, but it looks not like clean solution. We can fix it with regexps. Not sure if we should. But bytecompiler doesn't like nil as arglist.

**Comment by conao3** [comment]
```emacs-lisp
(defun some-name nil
  27)
;;=> some-name

(some-name)
;;=> 27
```
really? I can define from the expression and could eval normally.

**Comment by conao3** [comment]
save below file as `~/dev/tmp/defun-nil.el`
```emacs-lisp
(defun some-name-byte-compile nil
  27)

(princ (some-name-byte-compile))
```
and eval below. It seems works well for me.
```emacs-lisp
(byte-compile-file "~/dev/tmp/defun-nil.el")
;;=> t

(load "~/dev/tmp/defun-nil.elc")
;;=> 27
;;   t
```

**Comment by s-kostyaev** [comment]
Will check it later. Which emacs version do you use? I use emacs 28. Maybe it's my fault.

**Comment by conao3** [comment]
I use Emacs 27 on linux and `(emacs-version)` returns like below.
```
(emacs-version)
;;=> "GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3)
;;    of 2020-08-29"
```

**Comment by s-kostyaev** [comment]
Looks like it works fine. Sorry for wasting your time.

**Comment by conao3** [comment]
ok, nothing bad. Welcome comments if you have any issues.
